### ISSUE TITLE
"byteCount" get the wrong value after caching multiple times on the same key

### ISSUE THREAD

**Issue by vietstone** [tumblr/TMCache#79]
A simple example:

    self.myDiskCache = [[TMDiskCache alloc] initWithName:@"myDiskCache"];

    UIImage *myImg = .....;  // 5MB
    
    // call cache multiple times
    dispatch_async(self.mySerialQueue, ^{
        for (int i=0; i<10; i++) {
                [self.myDiskCache setObject:myImg forKey:@"myKey" block:^(TMDiskCache *cache, NSString *key, id<NSCoding> object, NSURL *fileURL) {
                        NSLog(@"%f MB", cache.byteCount/pow(2., 20.));
                }];
        }
    });

The expectation outputs is "5 MB" for all.

But the chain is 5 MB, 10 MB, ... 50 MB.

**Comment by sudeepsidhu** [comment]
I opened an issue for this (with the fix) a while back, https://github.com/tumblr/TMCache/issues/42

Guess I should do a PR?

**Comment by vietstone** [comment]
wow, why hasn't that fix been added after a long time? :D

**Comment by segiddins** [comment]
Well, I don't think there's been a PR yet?

**Comment by irace** [comment]
Fixed: https://github.com/tumblr/TMCache/pull/82
