### ISSUE TITLE
disscuss about thread safe

### ISSUE THREAD

**Issue by luoyibu** [tumblr/TMCache#80]
Forgive my pool english.
I know that elements stored in TMCache is thread safe. But, is there a way to ensure that objects returned by TMCache is thread safe, such as array or dictionary.
Just like this : 
I get a array from TMCache in thread A, and then in thread B, I remove an object from the array while it was traversing the array in thread A.  Then I get a crash.

I wish you can understand my express, my English is pool.

**Comment by irace** [comment]
`TMCache` is thread-safe in that _it_ can be accessed from multiple threads. Once you get objects _out_ of `TMCache`, however, you’re on your own.

`NSArray` is _not_ thread-safe so you can't treat it as such just because it came from `TMCache`.

**Comment by luoyibu** [comment]
Yes, you are right. I know that I should ensure the thread safe of NSArray by myself, and I also know how to get it by GCD.   
But what I was discussing about is that can we get this for the users who are not familiar with thread safe.   Or, just encapsulate the functionality that keep objects came from TMCache to be thread safe.   
I just want to get some advice if it was possible.

**Comment by irace** [comment]
It's outside the scope of this project. I'm sure you could find thread-safe collection classes that you could use in conjunction with `TMCache`, but they don't belong in `TMCache` proper.
