### ISSUE TITLE
No changelog for 2.0?

### ISSUE THREAD

**Issue by ryanmaxwell** [tumblr/TMCache#84]
Hi - I've noticed 2.0 is released on cocoapods. Being a major version number, I assumed it would contain breaking changes. However - I don't see any changes (or mention) in the changelog? Also, at https://github.com/tumblr/TMCache/releases it still lists 1.2.3 as the "latest release" ?

**Comment by irace** [comment]
Thanks for flagging this up – I will add release notes tomorrow.

**Comment by irace** [comment]
Here you go: https://github.com/tumblr/TMCache/releases/tag/2.0.0
