### ISSUE TITLE
Advice on usage for offline solution

### ISSUE THREAD

**Issue by DRosadoYew** [tumblr/TMCache#88]
Hey everyone, not actually an issue, would just appreciate your opinion on this.

Kind of in a hurry to implement a solution for an app that does the usual data fetching from a REST like API but also requires an offline mode and persistence on disk (i.e. available between restarts). I'd say there's plenty of data (mostly text, as images are being addressed by SDWebImage), it's a wordpress website.

I'm trying to avoid the Core Data solution and was wondering if TMCache would be ok for it. Assuming that all my model objects conform to NSCoding, on every request i'd get the data from the cache and present it on screen, if available. Then would fetch the latest data from the API and cache it, using the url as key.
Also thought of including a pre-loaded cache in the app bundle.

Do you see any major problems with this?

Thank you for your time

**Comment by blankyao** [comment]
TMCache is a good choice, and with TMCache, you don't need to implement NSCoding protocol by yourself.

**Comment by irace** [comment]
Yes, `TMCache` will work fine for this use case.

Please keep in mind, however, that `TMCache` is deprecated. It'll work fine for your needs but it might be worth looking for an alternative for long-term, strategic use.

**Comment by DRosadoYew** [comment]
Will do. Thank you
