### ISSUE TITLE
TMDiskCache's enumerateObjectsWithBlock doesn't return objects

### ISSUE THREAD

**Issue by iwasrobbed** [tumblr/TMCache#89]
In the implementation for `enumerateObjectsWithBlock:completionBlock:`, the expanded `TMDiskCacheObjectBlock` is explicitly returning `nil` when enumerating over the keys, so effectively this enumerateObjects.. method is just for returning keys and file URLs, but no objects.

``` objC
for (NSString *key in keysSortedByDate) {
    NSURL *fileURL = [strongSelf encodedFileURLForKey:key];
    // Where block arguments are: 
    // TMDiskCache *cache, NSString *key, id <NSCoding> object, NSURL *fileURL
    block(strongSelf, key, nil, fileURL);
}
```

Is there a reason for doing this or should this enumeration method be renamed if it was intended to only be used for keys?

**Comment by brianmichel** [comment]
Hmm, this seems odd, however TMCache is no longer in active maintenance, please see [here](http://cocoa.tumblr.com/post/118790665043/tmcache-is-no-longer-being-actively-maintained) for an alternative to satisfy your needs.
